spring:
  application:
    name: micro-eureka-serverc
server: 
  port: 8083
eureka: 
  instance: 
    appname: ${spring.application.name}
    prefre-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/
logger:
  config: 
    classpath: logback.xml
  path: /Users/zhou/Desktop